Takagi/launch localization on psim
autowarefoundation/autoware_launch pull request #1094
Opened 2024-07-26 07:18 UTC by yuki-takagi-66

## Description

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Interface changes

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2024-07-26 08:25 UTC, takayuki5168 approved these changes

2024-07-26 10:22 UTC, kosuke55 approved these changes

2024-07-26 10:24 UTC, shmpwk approved these changes

2024-07-29 02:52 UTC, mitsudome-r commented
Could you explain why you want to launch Localization when using Psim?
My understanding is that PSim is used to test Planning/Control when Perception/Localization outputs are ideal.
Are there any reasons why we are launching localization modules instead of changing algorithms inside PSim for calculating odometry and acceleration?

My concern is that if a developer launch psim locally with `scenario_simulator=false`, there would be a risk that a bug inside localization modules (e.g., ekf) would impact the result of planning/control modules, which would ruin the purpose of psim.

2024-07-29 03:37 UTC, yukkysaito requested changes
I will block it to prevent it from being merged.

While PSim used the Component Interface, it is concerning that it will now depend on the internal interfaces of Localization. The role of PSim, as I understand it, is to test Planning/Control under the ideal outputs of Localization/Perception. If its role is to be expanded this much, I think it warrants further discussion.

2024-08-15 04:56 UTC, yuki-takagi-66 commented
@yukkysaito 
Thank you.
As we discussed internally, we need to achieve the following two goals: 
"maintain a simulator environment whose only dependent module is planning/control" and "evaluate planning/control modules, considering the characteristics of localization in a closed loop."
To achieve these two goals, the preceding PR https://github.com/autowarefoundation/autoware_launch/pull/1106 provided a mode-switching feature supporting three or more states.

2024-08-16 02:52 UTC, mitsudome-r approved these changes

2024-08-19 01:11 UTC, TakaHoribe approved these changes

2024-08-19 01:59 UTC, yukkysaito approved these changes

2024-08-19 08:51 UTC, merged