feat(autoware_launch): add predicted_path_checker package
autowarefoundation/autoware_launch pull request #385
Opened 2023-06-06 13:23 UTC by brkay54

## Description

Related links:
https://github.com/autowarefoundation/autoware.universe/pull/2528
https://github.com/autowarefoundation/autoware.universe/pull/3911
## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-09-30 22:22 UTC, brkay54 commented
Hi @TakaHoribe, the package was merged. Can you merge it?

2023-10-01 11:27 UTC, xmfcx requested changes
You need to open up another PR in the universe repos to add the required launch argument.

2023-10-01 11:27 UTC, xmfcx commented on autoware_launch/launch/components/tier4_control_component.launch.xml
> +    <arg name="predicted_path_checker_param_path" value="$(find-pkg-share autoware_launch)/config/control/predicted_path_checker/predicted_path_checker.param.yaml"/>
You are sending this `enable_predicted_path_checker` argument to the `control.launch.py` but you've forgotten to add it as a launch argument in the [previous PR](https://github.com/autowarefoundation/autoware.universe/pull/2528/files#r1342120806):

https://github.com/brkay54/autoware.universe/blob/1f2f0aaf82f103bef748e54448d2b2bf1fb93eef/launch/tier4_control_launch/launch/control.launch.py#L407

2023-10-01 14:06 UTC, xmfcx commented on autoware_launch/launch/components/tier4_control_component.launch.xml
> +    <arg name="predicted_path_checker_param_path" value="$(find-pkg-share autoware_launch)/config/control/predicted_path_checker/predicted_path_checker.param.yaml"/>
https://github.com/autowarefoundation/autoware.universe/pull/5186 is merged.

2023-10-01 14:07 UTC, xmfcx approved these changes

2023-10-01 14:07 UTC, merged

2023-10-01 16:29 UTC, TakaHoribe commented
@brkay54 @xmfcx Thank you! I checked the simulator works too.