feat(ekf_localizer): Add Simple1DFilter params to parameter file
autowarefoundation/autoware_launch pull request #710
Opened 2023-11-28 15:58 UTC by meliketanrikulu

## Description
Simple1DFilter parameters will be added to the parameter file to be able to change these parameters from the parameter file.

This PR related this PR: https://github.com/autowarefoundation/autoware.universe/pull/5707

## Tests performed

Not applicable.

## Effects on system behavior

Not applicable.

## Pre-review checklist for the PR author

The PR author **must** check the checkboxes below when creating the PR.

- [ ] I've confirmed the [contribution guidelines].
- [ ] The PR follows the [pull request guidelines].

## In-review checklist for the PR reviewers

The PR reviewers **must** check the checkboxes below before approval.

- [ ] The PR follows the [pull request guidelines].

## Post-review checklist for the PR author

The PR author **must** check the checkboxes below before merging.

- [ ] There are no open discussions or they are tracked via tickets.

After all checkboxes are checked, anyone who has write access can merge the PR.

[contribution guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/
[pull request guidelines]: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/

2023-12-21 12:38 UTC, kminoda reviewed
LGTM

2023-12-21 12:38 UTC, kminoda commented
@meliketanrikulu Please fix pre-commit

2023-12-27 00:27 UTC, KYabuuchi requested changes

2023-12-27 00:27 UTC, KYabuuchi commented on autoware_launch/config/localization/ekf_localizer.param.yaml
> +
There are unnecessary whitespaces. It is causing pre-commit violations.  Please remove them.

```suggestion

```

About pre-commit: https://autowarefoundation.github.io/autoware-documentation/main/contributing/pull-request-guidelines/ci-checks/#pre-commit

2024-01-15 05:00 UTC, KYabuuchi commented
@kminoda This PR has long been left undone. This is not good so I have committed myself to it.
Please review and approve this :pray:

2024-01-15 05:37 UTC, kminoda approved these changes

2024-01-15 05:54 UTC, KYabuuchi approved these changes

2024-01-15 05:55 UTC, merged